group: travis_latest
os: windows
# dist: xenial  # required for Python >= 3.7 (travis-ci/travis-ci#9069)
language: generic
cache: pip
python:
  #- 2.7
  #- 3.4
  #- 3.5
  #- 3.6
  - 3.7
matrix:
  allow_failures:
    - python: 2.7
    - python: nightly
    - python: pypy
    - python: pypy3
env:
  - REPO=MrAnde7son/Hunting
  
before-install:
  - choco install python
install:
  - pip -V
  - pip3 -V
  - pip2 -V
  #- pip install -r requirements.txt
  - pip install flake8  # pytest  # add other testing frameworks later
before_script:
  - URL=https://github.com/${REPO}
  - echo ; echo -n "flake8 testing of ${URL} on " ; python -V
  - git clone --depth=50 ${URL} ~/${REPO}  # --branch=master
  - cd ~/${REPO}
script:
  - echo stop the build if there are Python syntax errors or undefined names
  - echo ; echo -n "flake8 testing of ${URL} on " ; python -V
  - time flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics
  - echo exit-zero treats all errors as warnings.  The GitHub editor is 127 chars wide
  - time flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
  #- true  # pytest --capture=sys
notifications:
  on_success: change
  on_failure: change  # `always` will be the setting once code changes slow down
