# https://docs.travis-ci.com/user/reference/windows
# https://blog.travis-ci.com/2018-10-11-windows-early-release
os: windows
language: cpp  # 'python' is not yet supported
matrix:
  allow_failures:
    - python: 2.7
  include:
    - python: 2.7
      env: PY=C:\\Python27\\python.exe
      before_install: choco install python2
    - python: 3.6
      env: PY=py
      before_install: choco install python --version 3.6.8
    - python: 3.7
      env: PY=py
      before_install: choco install python
# env:
  # - REPO=cclauss/itinerant-tester-windows
install:
  - $PY --version
  - $PY -m pip install --upgrade pip
  #- $PY -m ensurepip --upgrade
  - $PY -m pip --version
  #- $PY -m pip install -r requirements.txt
  - choco install flake8 --source python
  #- $PY -m pip install --no-warn-script-location flake8  # pytest  # add other testing frameworks later
# before_script:
  # - URL=https://github.com/${REPO}
  # - echo ; echo -n "flake8 testing of ${URL} on " ; $PY --version
  #- git clone --depth=50 ${URL} ~/${REPO}  # --branch=master
  #- cd ~/${REPO}
script:
  - $PY -m flake8 --version
  - echo stop the build if there are Python syntax errors or undefined names
  - echo ; echo -n "flake8 testing of ${URL} on " ; $PY --version
  - $PY -m flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics
  - echo exit-zero treats all errors as warnings.  The GitHub editor is 127 chars wide
  - $PY -m flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
  #- true  # pytest --capture=sys
notifications:
  on_success: change
  on_failure: change  # `always` will be the setting once code changes slow down
